### ISSUE TITLE
HT/USDT Not available

### ISSUE THREAD

**Issue by Khaos116** [cernard/crypto-currency-monitor#3]
version is 0.0.2

![image](https://user-images.githubusercontent.com/11989916/119462422-e6b90400-bd6a-11eb-846c-3bf05db8305b.png)

**Comment by Khaos116** [comment]
另外SHIB的位数太多，导致后面显示不全

![image](https://user-images.githubusercontent.com/11989916/119462715-3d264280-bd6b-11eb-8704-a7f64a925487.png)
这个是Chrome 浏览器的插件看到的
![image](https://user-images.githubusercontent.com/11989916/119462985-7f4f8400-bd6b-11eb-8e54-559bd10d9708.png)

**Comment by caiyoufei** [comment]
![Uploading image.png…]()

**Comment by cernard** [comment]
谢谢反馈！0.0.x版本都是使用币安API，币安不支持的交易对自然也无法查看，而且当监控交易对过多后会触发币安的请求速率阈值限制。

这些问题在0.1.0分支中都得到了解决（重构软件，基于ccxt获得交易对市场价格，支持根据用户网络环境自动切换可用的交易所，无需科学上网），效果如下图：

<img width="320" alt="ff" src="https://user-images.githubusercontent.com/46954608/121766171-b521a480-cb82-11eb-93e8-14251111a619.png">

但由于我的身体原因需要手术住院，再加上需要准备面试跳槽，个人精力不足，暂时停止更新ccm这个软件，有时间了会恢复更新，有能力的可以自己clone 0.1.0分支编译。谢谢支持！

**Comment by Khaos116** [comment]
@cernard 感谢大佬，但是我不会exe，只会java和android，祝早日康复
